# Generated by Django 2.0.2 on 2020-07-15 02:07

import builtins
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['-create_time', builtins.id]},
        ),
        migrations.AlterModelTable(
            name='author',
            table='xiaoliuge',
        ),
    ]
