# Generated by Django 2.0.1 on 2020-07-16 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookorder',
            options={},
        ),
    ]
