# Generated by Django 2.0.1 on 2020-07-17 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('telephone', models.CharField(max_length=11, unique=True)),
                ('email', models.CharField(max_length=50, validators=[django.core.validators.EmailValidator(message='请输入正确的邮箱')])),
                ('username', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(6, message='用户名最少6位')])),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
